### ISSUE TITLE
why in bev

### ISSUE THREAD

**Issue by happydummy** [hht1996ok/ADMap#2]
hi, I'm wondering why in HD map construction everyone defaults to doing it in bev sapce instead of 3d space? Would that be bad?

**Comment by hht1996ok** [comment]
I think BEV can be better adapted to HD maps because HD map construction doesn't need height information, only 2D coordinates of map elements.  Using 3d space may not reduce the model accuracy, but it will increase the model inference time.

**Comment by happydummy** [comment]
thanks for your reply~
