### ISSUE TITLE
ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query'

### ISSUE THREAD

**Issue by xueqianxun** [hht1996ok/ADMap#4]
I used the 'https://github.com/hht1996ok/ADMap/tree/main/mmdet3d', an error occurred: ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query'.
I check the '.../hht1996ok/ADMap/tree/main/mmdet3d' files,  it looks like different from the official 'mmdetection3d'  and your 'mmdet3d' needs to be installed or compiled. So what should I do to use your 'mmdet3d' ?

**Comment by hht1996ok** [comment]
The following command can be used to compile mmdet3d: python setup.py develop 
Some of the components needed for ADMap have been added to our mmdet3d. However, the contents of the ‘ops’ are the same as official.

**Comment by xueqianxun** [comment]
@hht1996ok   hello, thanks for your help.
But, there is no "setup.py" in your file 'mmdet3d',  so I can not use 'python setup.py develop' in direction '.../ADMap/mmdet3d' .
Can you give me a more detailed explanation?
Thanks again !

**Comment by hht1996ok** [comment]
@xueqianxun  Sorry, we will upload the setup.py file as soon as possible.
